### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TaeJoongYoon**
Fix typo "Arnonymous" to "Anonymous"

Also, replace task with uploadTask cuz "task" variable is out of context.

I think It can cause confusion.

### CODE REVIEW

**Comment by arnauddorgans** [comment]
Hi ! thx for your support :) 
About "Arnonymous", in fact, it is my username :D

**Comment by TaeJoongYoon** [comment]
Ah! Okay :)

That's good username 👍

**Comment by TaeJoongYoon** [comment]
Then, Can I fix only “task”?

**Comment by arnauddorgans** [comment]
Sure :)

**Comment by TaeJoongYoon** [comment]
Okat :)

**Pull request closed without merging**
