### PR TITLE
Add Auth Examples

### PR DESCRIPTION
**Pull request by TaeJoongYoon**
Add examples to README about Auth

### CODE REVIEW

**Comment by TaeJoongYoon** [comment]
Oh, I'm sorry.

In updateEmail and delete,
Must replace `let auth = Auth.auth()` with `let auth = Auth.auth().currentUser?`

**Comment by TaeJoongYoon** [comment]
You're right.

Then can I split them?

**Comment by arnauddorgans** [comment]
What do you mean ? @TaeJoongYoon

**Comment by TaeJoongYoon** [comment]
### Auth
 Create:
  ```swift
 let auth = Auth.auth()
     
 // Create a password-based account
 auth.rx.createUser(withEmail: "xxx@xxx.com", password: "1q2w3e4r")
     .subscribe(onNext: { authResult in
         // User signed in
     }, onError: { error in
         // Uh-oh, an error occurred!
     }).disposed(by: disposeBag)
  // https://firebase.google.com/docs/auth/ios/password-auth
 ```
  Sign In:
  ```swift
 let auth = Auth.auth()
     
 // Sign in a user with an email address and password
 auth.rx.signIn(withEmail: "xxx@xxx.com", password: "1q2w3e4r")
     .subscribe(onNext: { authResult in
         // User signed in
     }, onError: { error in
         // Uh-oh, an error occurred!
     }).disposed(by: disposeBag)
  // https://firebase.google.com/docs/auth/ios/password-auth
 ```

### User

  Update Email:
  ```swift
 let auth = Auth.auth().currentUser?
     
 // Set a user's email address
 auth.rx.updateEmail(to: "xxx@xxx.com")
     .subscribe(onNext: {
         // Completed updating Email
     }, onError: { error in
         // Uh-oh, an error occurred!
     }).disposed(by: disposeBag)
  // https://firebase.google.com/docs/auth/ios/manage-users
 ```
  Delete:
  ```swift
 let auth = Auth.auth().currentUser?
     
 // Delete a user
 auth.rx.delete()
     .subscribe(onNext: {
         // User deleted
     }, onError: { error in
         // Uh-oh, an error occurred!
     }).disposed(by: disposeBag)
  // https://firebase.google.com/docs/auth/ios/manage-users
 ```


I mean like this.

**Comment by arnauddorgans** [comment]
Yes ! maybe replace the wording "auth" with "user" for email address & delete overwise it's perfect

**Comment by TaeJoongYoon** [comment]
Yes :) I edit it.

**Comment by arnauddorgans** [comment]
you have to replace auth.rx.updateEmail => user.rx.updateEmail and auth.rx.delete() => user.rx.delete()

**Comment by TaeJoongYoon** [comment]
I'm so sorry... I replace them

**Comment by arnauddorgans** [comment]
perfect! thx for your help :)

**Pull request merged**
